// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Homelab.LinuxServer.Inputs
{

    /// <summary>
    /// Port arguments for the service.
    /// </summary>
    public sealed class HeimdallPortsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// External port to expose container port 80.
        /// </summary>
        [Input("http")]
        public Input<double>? Http { get; set; }

        /// <summary>
        /// External port to expose container port 443.
        /// </summary>
        [Input("https")]
        public Input<double>? Https { get; set; }

        public HeimdallPortsArgs()
        {
        }
    }
}
