// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Homelab.K8s.LinuxServer.Inputs
{

    /// <summary>
    /// Radarr persistence options
    /// </summary>
    public sealed class RadarrPersistenceArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration persistence arguments
        /// </summary>
        [Input("config")]
        public Union<Input<Pulumi.Homelab.K8s.Inputs.PersistentVolumeClaimExistingClaimArgs>, Input<Pulumi.Homelab.K8s.Inputs.PersistentVolumeClaimStorageClassArgs>>? Config { get; set; }

        /// <summary>
        /// Downloads persistence arguments
        /// </summary>
        [Input("downloads")]
        public Union<Input<Pulumi.Homelab.K8s.Inputs.PersistentVolumeClaimExistingClaimArgs>, Input<Pulumi.Homelab.K8s.Inputs.PersistentVolumeClaimStorageClassArgs>>? Downloads { get; set; }

        /// <summary>
        /// Movies persistence arguments
        /// </summary>
        [Input("movies")]
        public Union<Input<Pulumi.Homelab.K8s.Inputs.PersistentVolumeClaimExistingClaimArgs>, Input<Pulumi.Homelab.K8s.Inputs.PersistentVolumeClaimStorageClassArgs>>? Movies { get; set; }

        public RadarrPersistenceArgs()
        {
        }
    }
}
