# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: homelab
displayName: Homelab
description: Popular homelab applications for docker and kubernetes
publisher: UnstoppableMango
keywords:
  - category/cloud
  - category/infrastructure
  - kind/component
  - pulumi
  - kubernetes
  - k8s
  - docker
  - homelab
repository: https://github.com/unmango/pulumi-homelab
pluginDownloadUrl: https://github.com/unmango/pulumi-homelab/releases/download/${VERSION}
resources:
  homelab:index:StaticPage:
    isComponent: true
    inputProperties:
      indexContent:
        type: string
        description: The HTML content for index.html.
    requiredInputs:
      - indexContent
    properties:
      bucket:
        "$ref": "/aws/v4.0.0/schema.json#/resources/aws:s3%2Fbucket:Bucket"
        description: The bucket resource.
      websiteUrl:
        type: string
        description: The website URL.
    required:
      - bucket
      - websiteUrl
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Aws: 4.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/unmango/pulumi-homelab/sdk/go/homelab
  nodejs:
    packageName: "@unmango/pulumi-homelab"
    dependencies:
      "@pulumi/aws": "^4.0.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-aws: ">=4.0.0,<5.0.0"
