# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: homelab
displayName: Homelab
description: Popular homelab applications for docker and kubernetes
publisher: UnstoppableMango
keywords:
  - category/cloud
  - category/infrastructure
  - kind/component
  - pulumi
  - kubernetes
  - k8s
  - docker
  - homelab
repository: https://github.com/unmango/pulumi-homelab
pluginDownloadUrl: https://github.com/unmango/pulumi-homelab/releases/download/${VERSION}
types:
  homelab:docker:RestartPolicy:
    description: Container restart policy.
    type: string
    enum:
      - name: Always
        value: always
      - name: "No"
        value: "no"
      - name: OnFailure
        value: on-failure
      - name: UnlessStopped
        value: unless-stopped
  homelab:kubernetes:ServiceType:
    type: string
    description: Kubernetes service type.
    enum:
      - value: ExternalName
      - value: ClusterIP
      - value: NodePort
      - value: LoadBalancer
  homelab:kubernetes/linuxserver:HeimdallService:
    type: object
    description: Arguments for the kubernetes service.
    properties:
      ports:
        "$ref": "#/types/homelab:linuxserver:HeimdallPorts"
        description: Port arguments for the container.
      type:
        # TODO: Something about this ref isn't right
        # "$ref": "/kubernetes/v3.0.0/schema.json#/types/kubernetes:core%2Fv1:ServiceSpecType"
        "$ref": "#/types/homelab:kubernetes:ServiceType"
        description: Type of service to create.
  homelab:kubernetes/linuxserver:HeimdallPersistence:
    type: object
    description: Heimdall persistence options.
    properties:
      accessModes:
        type: array
        description: Access modes for the persistent volume claim template.
        items:
          type: string
      enabled:
        type: boolean
        description: Whether to enable persistence or not.
        default: false
      size:
        type: string
        description: Size of the volume to request from the storage class.
        default: 1Gi
      storageClass:
        type: string
        description: Name of the storage class to use in the persistent volume claim template.
  homelab:linuxserver:HeimdallPorts:
    description: Port arguments for the service.
    type: object
    properties:
      http:
        type: number
        description: External port to expose container port 80.
      https:
        type: number
        description: External port to expose container port 443.
resources:
  homelab:docker/linuxserver:Heimdall:
    isComponent: true
    description: |
      Heimdall is a way to organise all those links to your most
      used web sites and web applications in a simple way.
      https://github.com/linuxserver/docker-heimdall
    inputProperties:
      configPath:
        type: string
        description: Host path to mount to /config in the container.
      pgid:
        type: string
        description: |
          The user id to run the container as.
          See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
      ports:
        "$ref": "#/types/homelab:linuxserver:HeimdallPorts"
        description: Port arguments for the container.
      puid:
        type: string
        description: |
          The group id to run the container as.
          See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
      restart:
        "$ref": "#/types/homelab:docker:RestartPolicy"
        description: Container restart policy.
      tz:
        type: string
        description: The timezone to use.
    properties:
      container:
        "$ref": "/docker/v3.0.0/schema.json#/resources/docker:index%2Fcontainer:Container"
        description: Heimdall container resource.
      image:
        "$ref": "/docker/v3.0.0/schema.json#/resources/docker:index%2fremoteImage:RemoteImage"
        description: Linuxserver Heimdall image resource.
    required:
      - container
      - image
  homelab:kubernetes/linuxserver:Heimdall:
    isComponent: true
    description: |
      Heimdall is a way to organise all those links to your most
      used web sites and web applications in a simple way.
      https://github.com/linuxserver/docker-heimdall
    inputProperties:
      namespace:
        type: string
        description: The namespace to put resources in.
      persistence:
        "$ref": "#/types/homelab:kubernetes/linuxserver:HeimdallPersistence"
        description: Heidmall persistence options.
      pgid:
        type: string
        description: |
          The user id to run the container as.
          See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
      puid:
        type: string
        description: |
          The group id to run the container as.
          See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
      service:
        "$ref": "#/types/homelab:kubernetes/linuxserver:HeimdallService"
        description: Arguments for the kubernetes service.
      tz:
        type: string
        description: The timezone to use.
    properties:
      service:
        "$ref": "/kubernetes/v3.0.0/schema.json#/resources/kubernetes:core%2Fv1:Service"
        description: Heimdall service object.
      statefulSet:
        "$ref": "/kubernetes/v3.0.0/schema.json#/resources/kubernetes:apps%2fv1:StatefulSet"
        description: Heimdall stateful set object.
    required:
      - service
      - statefulSet
language:
  csharp:
    rootNamespace: UnMango
    dictionaryConstructors: true
    namespaces:
      "": Provider
      docker: Docker
      docker/linuxserver: Docker.LinuxServer
      kubernetes: Kubernetes
      kubernetes/linuxserver: Kubernetes.LinuxServer
      linuxserver: LinuxServer
    packageReferences:
      Pulumi: 3.*
      Pulumi.Docker: 3.*
      Pulumi.Kubernetes: 3.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/unmango/pulumi-homelab/sdk/go/homelab
  nodejs:
    packageName: "@unmango/pulumi-homelab"
    dependencies:
      "@pulumi/docker": "^3.0.0"
      "@pulumi/kubernetes": "^3.0.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    packageName: unmango_pulumi_homelab
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-docker: ">=3.0.0,<4.0.0"
      pulumi-kubernetes: ">=3.0.0,<4.0.0"
