// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const RestartPolicy = {
    Always: "always",
    No: "no",
    OnFailure: "on-failure",
    UnlessStopped: "unless-stopped",
} as const;

/**
 * Container restart policy.
 */
export type RestartPolicy = (typeof RestartPolicy)[keyof typeof RestartPolicy];
