# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from ... import docker
from ... import linuxserver as _linuxserver
import pulumi_docker

__all__ = ['HeimdallArgs', 'Heimdall']

@pulumi.input_type
class HeimdallArgs:
    def __init__(__self__, *,
                 config_path: Optional[pulumi.Input[str]] = None,
                 pgid: Optional[pulumi.Input[str]] = None,
                 ports: Optional[pulumi.Input['_linuxserver.HeimdallPortsArgs']] = None,
                 puid: Optional[pulumi.Input[str]] = None,
                 restart: Optional[pulumi.Input['_docker.RestartPolicy']] = None,
                 tz: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a Heimdall resource.
        :param pulumi.Input[str] config_path: Host path to mount to /config in the container.
        :param pulumi.Input[str] pgid: The user id to run the container as.
               See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
        :param pulumi.Input['_linuxserver.HeimdallPortsArgs'] ports: Port arguments for the container.
        :param pulumi.Input[str] puid: The group id to run the container as.
               See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
        :param pulumi.Input['_docker.RestartPolicy'] restart: Container restart policy.
        :param pulumi.Input[str] tz: The timezone to use.
        """
        if config_path is not None:
            pulumi.set(__self__, "config_path", config_path)
        if pgid is not None:
            pulumi.set(__self__, "pgid", pgid)
        if ports is not None:
            pulumi.set(__self__, "ports", ports)
        if puid is not None:
            pulumi.set(__self__, "puid", puid)
        if restart is not None:
            pulumi.set(__self__, "restart", restart)
        if tz is not None:
            pulumi.set(__self__, "tz", tz)

    @property
    @pulumi.getter(name="configPath")
    def config_path(self) -> Optional[pulumi.Input[str]]:
        """
        Host path to mount to /config in the container.
        """
        return pulumi.get(self, "config_path")

    @config_path.setter
    def config_path(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "config_path", value)

    @property
    @pulumi.getter
    def pgid(self) -> Optional[pulumi.Input[str]]:
        """
        The user id to run the container as.
        See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
        """
        return pulumi.get(self, "pgid")

    @pgid.setter
    def pgid(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "pgid", value)

    @property
    @pulumi.getter
    def ports(self) -> Optional[pulumi.Input['_linuxserver.HeimdallPortsArgs']]:
        """
        Port arguments for the container.
        """
        return pulumi.get(self, "ports")

    @ports.setter
    def ports(self, value: Optional[pulumi.Input['_linuxserver.HeimdallPortsArgs']]):
        pulumi.set(self, "ports", value)

    @property
    @pulumi.getter
    def puid(self) -> Optional[pulumi.Input[str]]:
        """
        The group id to run the container as.
        See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
        """
        return pulumi.get(self, "puid")

    @puid.setter
    def puid(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "puid", value)

    @property
    @pulumi.getter
    def restart(self) -> Optional[pulumi.Input['_docker.RestartPolicy']]:
        """
        Container restart policy.
        """
        return pulumi.get(self, "restart")

    @restart.setter
    def restart(self, value: Optional[pulumi.Input['_docker.RestartPolicy']]):
        pulumi.set(self, "restart", value)

    @property
    @pulumi.getter
    def tz(self) -> Optional[pulumi.Input[str]]:
        """
        The timezone to use.
        """
        return pulumi.get(self, "tz")

    @tz.setter
    def tz(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "tz", value)


class Heimdall(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 config_path: Optional[pulumi.Input[str]] = None,
                 pgid: Optional[pulumi.Input[str]] = None,
                 ports: Optional[pulumi.Input[pulumi.InputType['_linuxserver.HeimdallPortsArgs']]] = None,
                 puid: Optional[pulumi.Input[str]] = None,
                 restart: Optional[pulumi.Input['_docker.RestartPolicy']] = None,
                 tz: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Heimdall is a way to organise all those links to your most
        used web sites and web applications in a simple way.
        https://github.com/linuxserver/docker-heimdall

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] config_path: Host path to mount to /config in the container.
        :param pulumi.Input[str] pgid: The user id to run the container as.
               See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
        :param pulumi.Input[pulumi.InputType['_linuxserver.HeimdallPortsArgs']] ports: Port arguments for the container.
        :param pulumi.Input[str] puid: The group id to run the container as.
               See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
        :param pulumi.Input['_docker.RestartPolicy'] restart: Container restart policy.
        :param pulumi.Input[str] tz: The timezone to use.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[HeimdallArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Heimdall is a way to organise all those links to your most
        used web sites and web applications in a simple way.
        https://github.com/linuxserver/docker-heimdall

        :param str resource_name: The name of the resource.
        :param HeimdallArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(HeimdallArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 config_path: Optional[pulumi.Input[str]] = None,
                 pgid: Optional[pulumi.Input[str]] = None,
                 ports: Optional[pulumi.Input[pulumi.InputType['_linuxserver.HeimdallPortsArgs']]] = None,
                 puid: Optional[pulumi.Input[str]] = None,
                 restart: Optional[pulumi.Input['_docker.RestartPolicy']] = None,
                 tz: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.plugin_download_url is None:
            opts.plugin_download_url = _utilities.get_plugin_download_url()
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = HeimdallArgs.__new__(HeimdallArgs)

            __props__.__dict__["config_path"] = config_path
            __props__.__dict__["pgid"] = pgid
            __props__.__dict__["ports"] = ports
            __props__.__dict__["puid"] = puid
            __props__.__dict__["restart"] = restart
            __props__.__dict__["tz"] = tz
            __props__.__dict__["container"] = None
            __props__.__dict__["image"] = None
        super(Heimdall, __self__).__init__(
            'homelab:docker/linuxserver:Heimdall',
            resource_name,
            __props__,
            opts,
            remote=True)

    @property
    @pulumi.getter
    def container(self) -> pulumi.Output['pulumi_docker.Container']:
        """
        Heimdall container resource.
        """
        return pulumi.get(self, "container")

    @property
    @pulumi.getter
    def image(self) -> pulumi.Output['pulumi_docker.RemoteImage']:
        """
        Linuxserver Heimdall image resource.
        """
        return pulumi.get(self, "image")

