// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.UnMango.Homelab.Kubernetes.LinuxServer.Inputs
{

    /// <summary>
    /// Arguments for the kubernetes service.
    /// </summary>
    public sealed class HeimdallServiceArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Port arguments for the container.
        /// </summary>
        [Input("ports")]
        public Input<Pulumi.UnMango.Homelab.LinuxServer.Inputs.HeimdallPortsArgs>? Ports { get; set; }

        /// <summary>
        /// Type of service to create.
        /// </summary>
        [Input("type")]
        public Input<Pulumi.UnMango.Homelab.Kubernetes.ServiceType>? Type { get; set; }

        public HeimdallServiceArgs()
        {
        }
    }
}
