# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import unmango_pulumi_homelab.docker as __docker
    docker = __docker
    import unmango_pulumi_homelab.kubernetes as __kubernetes
    kubernetes = __kubernetes
    import unmango_pulumi_homelab.linuxserver as __linuxserver
    linuxserver = __linuxserver
else:
    docker = _utilities.lazy_import('unmango_pulumi_homelab.docker')
    kubernetes = _utilities.lazy_import('unmango_pulumi_homelab.kubernetes')
    linuxserver = _utilities.lazy_import('unmango_pulumi_homelab.linuxserver')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "homelab",
  "mod": "docker/linuxserver",
  "fqn": "unmango_pulumi_homelab.docker.linuxserver",
  "classes": {
   "homelab:docker/linuxserver:Heimdall": "Heimdall"
  }
 },
 {
  "pkg": "homelab",
  "mod": "kubernetes/linuxserver",
  "fqn": "unmango_pulumi_homelab.kubernetes.linuxserver",
  "classes": {
   "homelab:kubernetes/linuxserver:Heimdall": "Heimdall"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "homelab",
  "token": "pulumi:providers:homelab",
  "fqn": "unmango_pulumi_homelab",
  "class": "Provider"
 }
]
"""
)
