// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.UnMango.Homelab.Docker.LinuxServer
{
    /// <summary>
    /// Heimdall is a way to organise all those links to your most
    /// used web sites and web applications in a simple way.
    /// https://github.com/linuxserver/docker-heimdall
    /// </summary>
    [HomelabResourceType("homelab:docker/linuxserver:Heimdall")]
    public partial class Heimdall : Pulumi.ComponentResource
    {
        /// <summary>
        /// Heimdall container resource.
        /// </summary>
        [Output("container")]
        public Output<Pulumi.Docker.Container> Container { get; private set; } = null!;

        /// <summary>
        /// Linuxserver Heimdall image resource.
        /// </summary>
        [Output("image")]
        public Output<Pulumi.Docker.RemoteImage> Image { get; private set; } = null!;


        /// <summary>
        /// Create a Heimdall resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Heimdall(string name, HeimdallArgs? args = null, ComponentResourceOptions? options = null)
            : base("homelab:docker/linuxserver:Heimdall", name, args ?? new HeimdallArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/unmango/pulumi-homelab/releases/download/${VERSION}",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class HeimdallArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Host path to mount to /config in the container.
        /// </summary>
        [Input("configPath")]
        public Input<string>? ConfigPath { get; set; }

        /// <summary>
        /// The user id to run the container as.
        /// See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
        /// </summary>
        [Input("pgid")]
        public Input<string>? Pgid { get; set; }

        /// <summary>
        /// Port arguments for the container.
        /// </summary>
        [Input("ports")]
        public Input<Pulumi.UnMango.Homelab.LinuxServer.Inputs.HeimdallPortsArgs>? Ports { get; set; }

        /// <summary>
        /// The group id to run the container as.
        /// See https://github.com/linuxserver/docker-heimdall#user--group-identifiers
        /// </summary>
        [Input("puid")]
        public Input<string>? Puid { get; set; }

        /// <summary>
        /// Container restart policy.
        /// </summary>
        [Input("restart")]
        public Input<Pulumi.UnMango.Homelab.Docker.RestartPolicy>? Restart { get; set; }

        /// <summary>
        /// The timezone to use.
        /// </summary>
        [Input("tz")]
        public Input<string>? Tz { get; set; }

        public HeimdallArgs()
        {
        }
    }
}
