# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .provider import *
from .radarr import *
from .static_page import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "homelab",
  "mod": "index",
  "fqn": "pulumi_homelab",
  "classes": {
   "homelab:index:StaticPage": "StaticPage"
  }
 },
 {
  "pkg": "homelab",
  "mod": "index/kubernetes/linuxserver",
  "fqn": "pulumi_homelab",
  "classes": {
   "homelab:index/kubernetes/linuxserver:Radarr": "Radarr"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "homelab",
  "token": "pulumi:providers:homelab",
  "fqn": "pulumi_homelab",
  "class": "Provider"
 }
]
"""
)
