# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .static_page import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_homelab.k8s as __k8s
    k8s = __k8s
else:
    k8s = _utilities.lazy_import('pulumi_homelab.k8s')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "homelab",
  "mod": "index",
  "fqn": "pulumi_homelab",
  "classes": {
   "homelab:index:StaticPage": "StaticPage"
  }
 },
 {
  "pkg": "homelab",
  "mod": "k8s/linuxserver",
  "fqn": "pulumi_homelab.k8s.linuxserver",
  "classes": {
   "homelab:k8s/linuxserver:Radarr": "Radarr"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "homelab",
  "token": "pulumi:providers:homelab",
  "fqn": "pulumi_homelab",
  "class": "Provider"
 }
]
"""
)
