# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'DeploymentStrategyType',
    'ServiceType',
]


class DeploymentStrategyType(str, Enum):
    RECREATE = "Recreate"
    ROLLING = "Rolling"


class ServiceType(str, Enum):
    CLUSTER_IP = "ClusterIP"
    LOAD_BALANCER = "LoadBalancer"
