// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const KubernetesDeploymentStrategyType = {
    Recreate: "Recreate",
    Rolling: "Rolling",
} as const;

export type KubernetesDeploymentStrategyType = (typeof KubernetesDeploymentStrategyType)[keyof typeof KubernetesDeploymentStrategyType];

export const KubernetesServiceType = {
    ClusterIP: "ClusterIP",
    LoadBalancer: "LoadBalancer",
} as const;

export type KubernetesServiceType = (typeof KubernetesServiceType)[keyof typeof KubernetesServiceType];
