// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Homelab.K8s.Inputs
{

    public sealed class ImageArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Registry to use for the image. e.g. 'lcsr.io'
        /// </summary>
        [Input("registry")]
        public Input<string>? Registry { get; set; }

        /// <summary>
        /// Repository to use for the image. e.g. 'linuxserver'
        /// </summary>
        [Input("repository")]
        public Input<string>? Repository { get; set; }

        /// <summary>
        /// Tag to use for the image. e.g. 'latest'
        /// </summary>
        [Input("tag")]
        public Input<string>? Tag { get; set; }

        public ImageArgs()
        {
        }
    }
}
