// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Homelab.K8s.Inputs
{

    /// <summary>
    /// Arguments for specifying an existing persistent volume claim.
    /// </summary>
    public sealed class PersistentVolumeClaimExistingClaimArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Existing volume claim to use.
        /// </summary>
        [Input("existingClaim", required: true)]
        public Input<string> ExistingClaim { get; set; } = null!;

        /// <summary>
        /// Path within the volume to mount.
        /// </summary>
        [Input("subPath")]
        public Input<string>? SubPath { get; set; }

        /// <summary>
        /// Type of persistent volume claim.
        /// Expected value is 'existingClaim'
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public PersistentVolumeClaimExistingClaimArgs()
        {
        }
    }
}
