// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Homelab.K8s.Inputs
{

    /// <summary>
    /// Options for creating a persistent volume claim from a storage class.
    /// </summary>
    public sealed class PersistentVolumeClaimStorageClassArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access mode for the volume.
        /// </summary>
        [Input("accessMode")]
        public Input<string>? AccessMode { get; set; }

        /// <summary>
        /// Size of the volume.
        /// </summary>
        [Input("size")]
        public Input<string>? Size { get; set; }

        /// <summary>
        /// Storage class to use to provision the volume.
        /// </summary>
        [Input("storageClass", required: true)]
        public Input<string> StorageClass { get; set; } = null!;

        /// <summary>
        /// Path within the volume to mount.
        /// </summary>
        [Input("subPath")]
        public Input<string>? SubPath { get; set; }

        /// <summary>
        /// Type of persistent volume claim.
        /// Expected value is 'storageClass'
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public PersistentVolumeClaimStorageClassArgs()
        {
            AccessMode = "ReadWriteOnce";
        }
    }
}
