// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Homelab.K8s.Inputs
{

    public sealed class ServiceArgs : Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("type", required: true)]
        public Input<Pulumi.Homelab.K8s.ServiceType> Type { get; set; } = null!;

        public ServiceArgs()
        {
        }
    }
}
