// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const ServiceType = {
    ExternalName: "ExternalName",
    ClusterIP: "ClusterIP",
    NodePort: "NodePort",
    LoadBalancer: "LoadBalancer",
} as const;

/**
 * Kubernetes service type.
 */
export type ServiceType = (typeof ServiceType)[keyof typeof ServiceType];
