// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package homelab

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type KubernetesDeployment struct {
	Strategy *KubernetesDeploymentStrategy `pulumi:"strategy"`
}

// KubernetesDeploymentInput is an input type that accepts KubernetesDeploymentArgs and KubernetesDeploymentOutput values.
// You can construct a concrete instance of `KubernetesDeploymentInput` via:
//
//          KubernetesDeploymentArgs{...}
type KubernetesDeploymentInput interface {
	pulumi.Input

	ToKubernetesDeploymentOutput() KubernetesDeploymentOutput
	ToKubernetesDeploymentOutputWithContext(context.Context) KubernetesDeploymentOutput
}

type KubernetesDeploymentArgs struct {
	Strategy KubernetesDeploymentStrategyPtrInput `pulumi:"strategy"`
}

func (KubernetesDeploymentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KubernetesDeployment)(nil)).Elem()
}

func (i KubernetesDeploymentArgs) ToKubernetesDeploymentOutput() KubernetesDeploymentOutput {
	return i.ToKubernetesDeploymentOutputWithContext(context.Background())
}

func (i KubernetesDeploymentArgs) ToKubernetesDeploymentOutputWithContext(ctx context.Context) KubernetesDeploymentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesDeploymentOutput)
}

func (i KubernetesDeploymentArgs) ToKubernetesDeploymentPtrOutput() KubernetesDeploymentPtrOutput {
	return i.ToKubernetesDeploymentPtrOutputWithContext(context.Background())
}

func (i KubernetesDeploymentArgs) ToKubernetesDeploymentPtrOutputWithContext(ctx context.Context) KubernetesDeploymentPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesDeploymentOutput).ToKubernetesDeploymentPtrOutputWithContext(ctx)
}

// KubernetesDeploymentPtrInput is an input type that accepts KubernetesDeploymentArgs, KubernetesDeploymentPtr and KubernetesDeploymentPtrOutput values.
// You can construct a concrete instance of `KubernetesDeploymentPtrInput` via:
//
//          KubernetesDeploymentArgs{...}
//
//  or:
//
//          nil
type KubernetesDeploymentPtrInput interface {
	pulumi.Input

	ToKubernetesDeploymentPtrOutput() KubernetesDeploymentPtrOutput
	ToKubernetesDeploymentPtrOutputWithContext(context.Context) KubernetesDeploymentPtrOutput
}

type kubernetesDeploymentPtrType KubernetesDeploymentArgs

func KubernetesDeploymentPtr(v *KubernetesDeploymentArgs) KubernetesDeploymentPtrInput {
	return (*kubernetesDeploymentPtrType)(v)
}

func (*kubernetesDeploymentPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**KubernetesDeployment)(nil)).Elem()
}

func (i *kubernetesDeploymentPtrType) ToKubernetesDeploymentPtrOutput() KubernetesDeploymentPtrOutput {
	return i.ToKubernetesDeploymentPtrOutputWithContext(context.Background())
}

func (i *kubernetesDeploymentPtrType) ToKubernetesDeploymentPtrOutputWithContext(ctx context.Context) KubernetesDeploymentPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesDeploymentPtrOutput)
}

type KubernetesDeploymentOutput struct{ *pulumi.OutputState }

func (KubernetesDeploymentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KubernetesDeployment)(nil)).Elem()
}

func (o KubernetesDeploymentOutput) ToKubernetesDeploymentOutput() KubernetesDeploymentOutput {
	return o
}

func (o KubernetesDeploymentOutput) ToKubernetesDeploymentOutputWithContext(ctx context.Context) KubernetesDeploymentOutput {
	return o
}

func (o KubernetesDeploymentOutput) ToKubernetesDeploymentPtrOutput() KubernetesDeploymentPtrOutput {
	return o.ToKubernetesDeploymentPtrOutputWithContext(context.Background())
}

func (o KubernetesDeploymentOutput) ToKubernetesDeploymentPtrOutputWithContext(ctx context.Context) KubernetesDeploymentPtrOutput {
	return o.ApplyT(func(v KubernetesDeployment) *KubernetesDeployment {
		return &v
	}).(KubernetesDeploymentPtrOutput)
}
func (o KubernetesDeploymentOutput) Strategy() KubernetesDeploymentStrategyPtrOutput {
	return o.ApplyT(func(v KubernetesDeployment) *KubernetesDeploymentStrategy { return v.Strategy }).(KubernetesDeploymentStrategyPtrOutput)
}

type KubernetesDeploymentPtrOutput struct{ *pulumi.OutputState }

func (KubernetesDeploymentPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KubernetesDeployment)(nil)).Elem()
}

func (o KubernetesDeploymentPtrOutput) ToKubernetesDeploymentPtrOutput() KubernetesDeploymentPtrOutput {
	return o
}

func (o KubernetesDeploymentPtrOutput) ToKubernetesDeploymentPtrOutputWithContext(ctx context.Context) KubernetesDeploymentPtrOutput {
	return o
}

func (o KubernetesDeploymentPtrOutput) Elem() KubernetesDeploymentOutput {
	return o.ApplyT(func(v *KubernetesDeployment) KubernetesDeployment { return *v }).(KubernetesDeploymentOutput)
}

func (o KubernetesDeploymentPtrOutput) Strategy() KubernetesDeploymentStrategyPtrOutput {
	return o.ApplyT(func(v *KubernetesDeployment) *KubernetesDeploymentStrategy {
		if v == nil {
			return nil
		}
		return v.Strategy
	}).(KubernetesDeploymentStrategyPtrOutput)
}

type KubernetesDeploymentStrategy struct {
	Type *string `pulumi:"type"`
}

// KubernetesDeploymentStrategyInput is an input type that accepts KubernetesDeploymentStrategyArgs and KubernetesDeploymentStrategyOutput values.
// You can construct a concrete instance of `KubernetesDeploymentStrategyInput` via:
//
//          KubernetesDeploymentStrategyArgs{...}
type KubernetesDeploymentStrategyInput interface {
	pulumi.Input

	ToKubernetesDeploymentStrategyOutput() KubernetesDeploymentStrategyOutput
	ToKubernetesDeploymentStrategyOutputWithContext(context.Context) KubernetesDeploymentStrategyOutput
}

type KubernetesDeploymentStrategyArgs struct {
	Type *KubernetesDeploymentStrategyType `pulumi:"type"`
}

func (KubernetesDeploymentStrategyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KubernetesDeploymentStrategy)(nil)).Elem()
}

func (i KubernetesDeploymentStrategyArgs) ToKubernetesDeploymentStrategyOutput() KubernetesDeploymentStrategyOutput {
	return i.ToKubernetesDeploymentStrategyOutputWithContext(context.Background())
}

func (i KubernetesDeploymentStrategyArgs) ToKubernetesDeploymentStrategyOutputWithContext(ctx context.Context) KubernetesDeploymentStrategyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesDeploymentStrategyOutput)
}

func (i KubernetesDeploymentStrategyArgs) ToKubernetesDeploymentStrategyPtrOutput() KubernetesDeploymentStrategyPtrOutput {
	return i.ToKubernetesDeploymentStrategyPtrOutputWithContext(context.Background())
}

func (i KubernetesDeploymentStrategyArgs) ToKubernetesDeploymentStrategyPtrOutputWithContext(ctx context.Context) KubernetesDeploymentStrategyPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesDeploymentStrategyOutput).ToKubernetesDeploymentStrategyPtrOutputWithContext(ctx)
}

// KubernetesDeploymentStrategyPtrInput is an input type that accepts KubernetesDeploymentStrategyArgs, KubernetesDeploymentStrategyPtr and KubernetesDeploymentStrategyPtrOutput values.
// You can construct a concrete instance of `KubernetesDeploymentStrategyPtrInput` via:
//
//          KubernetesDeploymentStrategyArgs{...}
//
//  or:
//
//          nil
type KubernetesDeploymentStrategyPtrInput interface {
	pulumi.Input

	ToKubernetesDeploymentStrategyPtrOutput() KubernetesDeploymentStrategyPtrOutput
	ToKubernetesDeploymentStrategyPtrOutputWithContext(context.Context) KubernetesDeploymentStrategyPtrOutput
}

type kubernetesDeploymentStrategyPtrType KubernetesDeploymentStrategyArgs

func KubernetesDeploymentStrategyPtr(v *KubernetesDeploymentStrategyArgs) KubernetesDeploymentStrategyPtrInput {
	return (*kubernetesDeploymentStrategyPtrType)(v)
}

func (*kubernetesDeploymentStrategyPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**KubernetesDeploymentStrategy)(nil)).Elem()
}

func (i *kubernetesDeploymentStrategyPtrType) ToKubernetesDeploymentStrategyPtrOutput() KubernetesDeploymentStrategyPtrOutput {
	return i.ToKubernetesDeploymentStrategyPtrOutputWithContext(context.Background())
}

func (i *kubernetesDeploymentStrategyPtrType) ToKubernetesDeploymentStrategyPtrOutputWithContext(ctx context.Context) KubernetesDeploymentStrategyPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesDeploymentStrategyPtrOutput)
}

type KubernetesDeploymentStrategyOutput struct{ *pulumi.OutputState }

func (KubernetesDeploymentStrategyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KubernetesDeploymentStrategy)(nil)).Elem()
}

func (o KubernetesDeploymentStrategyOutput) ToKubernetesDeploymentStrategyOutput() KubernetesDeploymentStrategyOutput {
	return o
}

func (o KubernetesDeploymentStrategyOutput) ToKubernetesDeploymentStrategyOutputWithContext(ctx context.Context) KubernetesDeploymentStrategyOutput {
	return o
}

func (o KubernetesDeploymentStrategyOutput) ToKubernetesDeploymentStrategyPtrOutput() KubernetesDeploymentStrategyPtrOutput {
	return o.ToKubernetesDeploymentStrategyPtrOutputWithContext(context.Background())
}

func (o KubernetesDeploymentStrategyOutput) ToKubernetesDeploymentStrategyPtrOutputWithContext(ctx context.Context) KubernetesDeploymentStrategyPtrOutput {
	return o.ApplyT(func(v KubernetesDeploymentStrategy) *KubernetesDeploymentStrategy {
		return &v
	}).(KubernetesDeploymentStrategyPtrOutput)
}
func (o KubernetesDeploymentStrategyOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KubernetesDeploymentStrategy) *string { return v.Type }).(pulumi.StringPtrOutput)
}

type KubernetesDeploymentStrategyPtrOutput struct{ *pulumi.OutputState }

func (KubernetesDeploymentStrategyPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KubernetesDeploymentStrategy)(nil)).Elem()
}

func (o KubernetesDeploymentStrategyPtrOutput) ToKubernetesDeploymentStrategyPtrOutput() KubernetesDeploymentStrategyPtrOutput {
	return o
}

func (o KubernetesDeploymentStrategyPtrOutput) ToKubernetesDeploymentStrategyPtrOutputWithContext(ctx context.Context) KubernetesDeploymentStrategyPtrOutput {
	return o
}

func (o KubernetesDeploymentStrategyPtrOutput) Elem() KubernetesDeploymentStrategyOutput {
	return o.ApplyT(func(v *KubernetesDeploymentStrategy) KubernetesDeploymentStrategy { return *v }).(KubernetesDeploymentStrategyOutput)
}

func (o KubernetesDeploymentStrategyPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KubernetesDeploymentStrategy) *string {
		if v == nil {
			return nil
		}
		return v.Type
	}).(pulumi.StringPtrOutput)
}

type KubernetesImageArgs struct {
	Registry   *string `pulumi:"registry"`
	Repository *string `pulumi:"repository"`
	Tag        *string `pulumi:"tag"`
}

// KubernetesImageArgsInput is an input type that accepts KubernetesImageArgsArgs and KubernetesImageArgsOutput values.
// You can construct a concrete instance of `KubernetesImageArgsInput` via:
//
//          KubernetesImageArgsArgs{...}
type KubernetesImageArgsInput interface {
	pulumi.Input

	ToKubernetesImageArgsOutput() KubernetesImageArgsOutput
	ToKubernetesImageArgsOutputWithContext(context.Context) KubernetesImageArgsOutput
}

type KubernetesImageArgsArgs struct {
	Registry   pulumi.StringPtrInput `pulumi:"registry"`
	Repository pulumi.StringPtrInput `pulumi:"repository"`
	Tag        pulumi.StringPtrInput `pulumi:"tag"`
}

func (KubernetesImageArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KubernetesImageArgs)(nil)).Elem()
}

func (i KubernetesImageArgsArgs) ToKubernetesImageArgsOutput() KubernetesImageArgsOutput {
	return i.ToKubernetesImageArgsOutputWithContext(context.Background())
}

func (i KubernetesImageArgsArgs) ToKubernetesImageArgsOutputWithContext(ctx context.Context) KubernetesImageArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesImageArgsOutput)
}

type KubernetesImageArgsOutput struct{ *pulumi.OutputState }

func (KubernetesImageArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KubernetesImageArgs)(nil)).Elem()
}

func (o KubernetesImageArgsOutput) ToKubernetesImageArgsOutput() KubernetesImageArgsOutput {
	return o
}

func (o KubernetesImageArgsOutput) ToKubernetesImageArgsOutputWithContext(ctx context.Context) KubernetesImageArgsOutput {
	return o
}

func (o KubernetesImageArgsOutput) Registry() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KubernetesImageArgs) *string { return v.Registry }).(pulumi.StringPtrOutput)
}

func (o KubernetesImageArgsOutput) Repository() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KubernetesImageArgs) *string { return v.Repository }).(pulumi.StringPtrOutput)
}

func (o KubernetesImageArgsOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KubernetesImageArgs) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

type KubernetesService struct {
	Name *string `pulumi:"name"`
	Type string  `pulumi:"type"`
}

// KubernetesServiceInput is an input type that accepts KubernetesServiceArgs and KubernetesServiceOutput values.
// You can construct a concrete instance of `KubernetesServiceInput` via:
//
//          KubernetesServiceArgs{...}
type KubernetesServiceInput interface {
	pulumi.Input

	ToKubernetesServiceOutput() KubernetesServiceOutput
	ToKubernetesServiceOutputWithContext(context.Context) KubernetesServiceOutput
}

type KubernetesServiceArgs struct {
	Name pulumi.StringPtrInput `pulumi:"name"`
	Type KubernetesServiceType `pulumi:"type"`
}

func (KubernetesServiceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*KubernetesService)(nil)).Elem()
}

func (i KubernetesServiceArgs) ToKubernetesServiceOutput() KubernetesServiceOutput {
	return i.ToKubernetesServiceOutputWithContext(context.Background())
}

func (i KubernetesServiceArgs) ToKubernetesServiceOutputWithContext(ctx context.Context) KubernetesServiceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesServiceOutput)
}

func (i KubernetesServiceArgs) ToKubernetesServicePtrOutput() KubernetesServicePtrOutput {
	return i.ToKubernetesServicePtrOutputWithContext(context.Background())
}

func (i KubernetesServiceArgs) ToKubernetesServicePtrOutputWithContext(ctx context.Context) KubernetesServicePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesServiceOutput).ToKubernetesServicePtrOutputWithContext(ctx)
}

// KubernetesServicePtrInput is an input type that accepts KubernetesServiceArgs, KubernetesServicePtr and KubernetesServicePtrOutput values.
// You can construct a concrete instance of `KubernetesServicePtrInput` via:
//
//          KubernetesServiceArgs{...}
//
//  or:
//
//          nil
type KubernetesServicePtrInput interface {
	pulumi.Input

	ToKubernetesServicePtrOutput() KubernetesServicePtrOutput
	ToKubernetesServicePtrOutputWithContext(context.Context) KubernetesServicePtrOutput
}

type kubernetesServicePtrType KubernetesServiceArgs

func KubernetesServicePtr(v *KubernetesServiceArgs) KubernetesServicePtrInput {
	return (*kubernetesServicePtrType)(v)
}

func (*kubernetesServicePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**KubernetesService)(nil)).Elem()
}

func (i *kubernetesServicePtrType) ToKubernetesServicePtrOutput() KubernetesServicePtrOutput {
	return i.ToKubernetesServicePtrOutputWithContext(context.Background())
}

func (i *kubernetesServicePtrType) ToKubernetesServicePtrOutputWithContext(ctx context.Context) KubernetesServicePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KubernetesServicePtrOutput)
}

type KubernetesServiceOutput struct{ *pulumi.OutputState }

func (KubernetesServiceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*KubernetesService)(nil)).Elem()
}

func (o KubernetesServiceOutput) ToKubernetesServiceOutput() KubernetesServiceOutput {
	return o
}

func (o KubernetesServiceOutput) ToKubernetesServiceOutputWithContext(ctx context.Context) KubernetesServiceOutput {
	return o
}

func (o KubernetesServiceOutput) ToKubernetesServicePtrOutput() KubernetesServicePtrOutput {
	return o.ToKubernetesServicePtrOutputWithContext(context.Background())
}

func (o KubernetesServiceOutput) ToKubernetesServicePtrOutputWithContext(ctx context.Context) KubernetesServicePtrOutput {
	return o.ApplyT(func(v KubernetesService) *KubernetesService {
		return &v
	}).(KubernetesServicePtrOutput)
}
func (o KubernetesServiceOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KubernetesService) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o KubernetesServiceOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v KubernetesService) string { return v.Type }).(pulumi.StringOutput)
}

type KubernetesServicePtrOutput struct{ *pulumi.OutputState }

func (KubernetesServicePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KubernetesService)(nil)).Elem()
}

func (o KubernetesServicePtrOutput) ToKubernetesServicePtrOutput() KubernetesServicePtrOutput {
	return o
}

func (o KubernetesServicePtrOutput) ToKubernetesServicePtrOutputWithContext(ctx context.Context) KubernetesServicePtrOutput {
	return o
}

func (o KubernetesServicePtrOutput) Elem() KubernetesServiceOutput {
	return o.ApplyT(func(v *KubernetesService) KubernetesService { return *v }).(KubernetesServiceOutput)
}

func (o KubernetesServicePtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KubernetesService) *string {
		if v == nil {
			return nil
		}
		return v.Name
	}).(pulumi.StringPtrOutput)
}

func (o KubernetesServicePtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *KubernetesService) *string {
		if v == nil {
			return nil
		}
		return &v.Type
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(KubernetesDeploymentOutput{})
	pulumi.RegisterOutputType(KubernetesDeploymentPtrOutput{})
	pulumi.RegisterOutputType(KubernetesDeploymentStrategyOutput{})
	pulumi.RegisterOutputType(KubernetesDeploymentStrategyPtrOutput{})
	pulumi.RegisterOutputType(KubernetesImageArgsOutput{})
	pulumi.RegisterOutputType(KubernetesServiceOutput{})
	pulumi.RegisterOutputType(KubernetesServicePtrOutput{})
}
