// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";

export interface DeploymentArgs {
    strategy?: pulumi.Input<inputs.DeploymentStrategyArgs>;
}

export interface DeploymentStrategyArgs {
    type?: pulumi.Input<enums.DeploymentStrategyType>;
}

export interface ImageArgsArgs {
    registry?: pulumi.Input<string>;
    repository?: pulumi.Input<string>;
    tag?: pulumi.Input<string>;
}

export interface ServiceArgs {
    name?: pulumi.Input<string>;
    type: pulumi.Input<enums.ServiceType>;
}
