// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Homelab.Inputs
{

    public sealed class KubernetesImageArgsArgs : Pulumi.ResourceArgs
    {
        [Input("registry")]
        public Input<string>? Registry { get; set; }

        [Input("repository")]
        public Input<string>? Repository { get; set; }

        [Input("tag")]
        public Input<string>? Tag { get; set; }

        public KubernetesImageArgsArgs()
        {
        }
    }
}
