// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../../types";
import * as utilities from "../../utilities";

export class Radarr extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'homelab:k8s/linuxserver:Radarr';

    /**
     * Returns true if the given object is an instance of Radarr.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Radarr {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Radarr.__pulumiType;
    }


    /**
     * Create a Radarr resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: RadarrArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["deployment"] = args ? (args.deployment ? pulumi.output(args.deployment).apply(inputs.k8s.deploymentArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["image"] = args ? args.image : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["namespace"] = args ? args.namespace : undefined;
            resourceInputs["service"] = args ? args.service : undefined;
        } else {
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Radarr.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Radarr resource.
 */
export interface RadarrArgs {
    deployment?: pulumi.Input<inputs.k8s.DeploymentArgs>;
    image?: pulumi.Input<string | inputs.k8s.ImageArgsArgs>;
    /**
     * Optional name override.
     */
    name?: pulumi.Input<string>;
    /**
     * Namespace to provision resources in.
     */
    namespace?: pulumi.Input<string>;
    service?: pulumi.Input<inputs.k8s.ServiceArgs>;
}
