// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package linuxserver

import (
	"github.com/unmango/pulumi-homelab/sdk/go/homelab/k8s"
)

// Radarr persistence options
type RadarrPersistence struct {
	// Configuration persistence arguments
	Config interface{} `pulumi:"config"`
	// Downloads persistence arguments
	Downloads interface{} `pulumi:"downloads"`
	// Movies persistence arguments
	Movies interface{} `pulumi:"movies"`
}

func init() {
}
