// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package linuxserver

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/unmango/pulumi-homelab/sdk/go/homelab/k8s"
)

type Radarr struct {
	pulumi.ResourceState
}

// NewRadarr registers a new resource with the given unique name, arguments, and options.
func NewRadarr(ctx *pulumi.Context,
	name string, args *RadarrArgs, opts ...pulumi.ResourceOption) (*Radarr, error) {
	if args == nil {
		args = &RadarrArgs{}
	}

	if args.Deployment != nil {
		args.Deployment = args.Deployment.ToDeploymentPtrOutput().ApplyT(func(v *k8s.Deployment) *k8s.Deployment { return v.Defaults() }).(k8s.DeploymentPtrOutput)
	}
	var resource Radarr
	err := ctx.RegisterRemoteComponentResource("homelab:k8s/linuxserver:Radarr", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type radarrArgs struct {
	// Arguments for the kubernetes deployment.
	Deployment *k8s.Deployment `pulumi:"deployment"`
	// Optional custom image to use.
	Image interface{} `pulumi:"image"`
	// Optional name override.
	Name *string `pulumi:"name"`
	// Namespace to provision resources in.
	Namespace *string `pulumi:"namespace"`
	// Arguments for the kubernetes service.
	Service *k8s.Service `pulumi:"service"`
}

// The set of arguments for constructing a Radarr resource.
type RadarrArgs struct {
	// Arguments for the kubernetes deployment.
	Deployment k8s.DeploymentPtrInput
	// Optional custom image to use.
	Image pulumi.Input
	// Optional name override.
	Name pulumi.StringPtrInput
	// Namespace to provision resources in.
	Namespace pulumi.StringPtrInput
	// Arguments for the kubernetes service.
	Service k8s.ServicePtrInput
}

func (RadarrArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*radarrArgs)(nil)).Elem()
}

type RadarrInput interface {
	pulumi.Input

	ToRadarrOutput() RadarrOutput
	ToRadarrOutputWithContext(ctx context.Context) RadarrOutput
}

func (*Radarr) ElementType() reflect.Type {
	return reflect.TypeOf((**Radarr)(nil)).Elem()
}

func (i *Radarr) ToRadarrOutput() RadarrOutput {
	return i.ToRadarrOutputWithContext(context.Background())
}

func (i *Radarr) ToRadarrOutputWithContext(ctx context.Context) RadarrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RadarrOutput)
}

// RadarrArrayInput is an input type that accepts RadarrArray and RadarrArrayOutput values.
// You can construct a concrete instance of `RadarrArrayInput` via:
//
//          RadarrArray{ RadarrArgs{...} }
type RadarrArrayInput interface {
	pulumi.Input

	ToRadarrArrayOutput() RadarrArrayOutput
	ToRadarrArrayOutputWithContext(context.Context) RadarrArrayOutput
}

type RadarrArray []RadarrInput

func (RadarrArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Radarr)(nil)).Elem()
}

func (i RadarrArray) ToRadarrArrayOutput() RadarrArrayOutput {
	return i.ToRadarrArrayOutputWithContext(context.Background())
}

func (i RadarrArray) ToRadarrArrayOutputWithContext(ctx context.Context) RadarrArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RadarrArrayOutput)
}

// RadarrMapInput is an input type that accepts RadarrMap and RadarrMapOutput values.
// You can construct a concrete instance of `RadarrMapInput` via:
//
//          RadarrMap{ "key": RadarrArgs{...} }
type RadarrMapInput interface {
	pulumi.Input

	ToRadarrMapOutput() RadarrMapOutput
	ToRadarrMapOutputWithContext(context.Context) RadarrMapOutput
}

type RadarrMap map[string]RadarrInput

func (RadarrMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Radarr)(nil)).Elem()
}

func (i RadarrMap) ToRadarrMapOutput() RadarrMapOutput {
	return i.ToRadarrMapOutputWithContext(context.Background())
}

func (i RadarrMap) ToRadarrMapOutputWithContext(ctx context.Context) RadarrMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RadarrMapOutput)
}

type RadarrOutput struct{ *pulumi.OutputState }

func (RadarrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Radarr)(nil)).Elem()
}

func (o RadarrOutput) ToRadarrOutput() RadarrOutput {
	return o
}

func (o RadarrOutput) ToRadarrOutputWithContext(ctx context.Context) RadarrOutput {
	return o
}

type RadarrArrayOutput struct{ *pulumi.OutputState }

func (RadarrArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Radarr)(nil)).Elem()
}

func (o RadarrArrayOutput) ToRadarrArrayOutput() RadarrArrayOutput {
	return o
}

func (o RadarrArrayOutput) ToRadarrArrayOutputWithContext(ctx context.Context) RadarrArrayOutput {
	return o
}

func (o RadarrArrayOutput) Index(i pulumi.IntInput) RadarrOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Radarr {
		return vs[0].([]*Radarr)[vs[1].(int)]
	}).(RadarrOutput)
}

type RadarrMapOutput struct{ *pulumi.OutputState }

func (RadarrMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Radarr)(nil)).Elem()
}

func (o RadarrMapOutput) ToRadarrMapOutput() RadarrMapOutput {
	return o
}

func (o RadarrMapOutput) ToRadarrMapOutputWithContext(ctx context.Context) RadarrMapOutput {
	return o
}

func (o RadarrMapOutput) MapIndex(k pulumi.StringInput) RadarrOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Radarr {
		return vs[0].(map[string]*Radarr)[vs[1].(string)]
	}).(RadarrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RadarrInput)(nil)).Elem(), &Radarr{})
	pulumi.RegisterInputType(reflect.TypeOf((*RadarrArrayInput)(nil)).Elem(), RadarrArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RadarrMapInput)(nil)).Elem(), RadarrMap{})
	pulumi.RegisterOutputType(RadarrOutput{})
	pulumi.RegisterOutputType(RadarrArrayOutput{})
	pulumi.RegisterOutputType(RadarrMapOutput{})
}
